---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
          - --branch=main
          - --branch=rc

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.1
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    rev: v2.1.0
    hooks:
      - id: epp-validate
      - id: erb-validate
      - id: puppet-lint
        args:
          - --fail-on-warnings
          - --with-context
          - --no-autoloader_layout-check
      # - id: puppet-validate
      - id: r10k-validate
      - id: ruby-validate
