---
name: Run PDK validation and unit tests

# yamllint disable-line rule:truthy
on:
  - push
  - pull_request

jobs:
  pdk-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run pdk validate
        uses: puppets-epic-show-theatre/action-pdk-validate@v1

      - name: Run pdk unit tests
        uses: puppets-epic-show-theatre/action-pdk-test-unit@v1
